#include "online_lookup.h"
#include "online_lookup_fetch.h"

const char OnlineLookupUsermod::_name[] PROGMEM = "OnlineLookup";
const char OnlineLookupUsermod::_enabled[] PROGMEM = "enabled";
const char OnlineLookupUsermod::_apiUrl[] PROGMEM = "apiUrl";

void OnlineLookupUsermod::performUpdate() {
  if (!WLED_CONNECTED) {
    launchName = "No WiFi";
    lastFetchFailed = true;
    lastHttpCode = 0;
    updateInProgress = false;
    return;
  }

#ifdef ARDUINO_ARCH_ESP32
  // AI: below section was generated by an AI
  String body;
  int status = 0;
  bool got = onlineLookupHttpsGet(apiUrl.c_str(), body, status);
  lastHttpCode = status;

  if (got) {
    DynamicJsonDocument doc(2048);
    DeserializationError error = deserializeJson(doc, body);

    bool ok = false;
    if (!error && doc["results"].is<JsonArray>() && doc["results"].size() > 0) {
      ok = applyLaunchLibraryResult(doc["results"][0]);
    }

    if (ok) {
      lastFetchFailed = false;
    } else {
      launchName = "Parse Err";
      lastFetchFailed = true;
    }
  } else if (status == 0 || status < 0) {
    launchName = "TLS/HTTP";
    lastFetchFailed = true;
  } else {
    launchName = "HTTP " + String(status);
    lastFetchFailed = true;
  }
  // AI: end
#endif

  updateInProgress = false;
}

static OnlineLookupUsermod online_lookup_usermod;
REGISTER_USERMOD(online_lookup_usermod);
