#include "online_lookup_fetch.h"

#ifdef ARDUINO_ARCH_ESP32
#include <WiFi.h>
#include <HTTPClient.h>
#include <WiFiClientSecure.h>
#include <WiFiClient.h>

// AI: below section was generated by an AI
bool onlineLookupHttpsGet(const char* url, String& outBody, int& outStatus) {
  outBody = "";
  outStatus = 0;
  if (!url || !url[0]) return false;

  const bool useTls = (strncmp(url, "https://", 8) == 0);
  WiFiClient *client = nullptr;
  WiFiClientSecure *secure = nullptr;

  if (useTls) {
    secure = new WiFiClientSecure();
    if (!secure) return false;
    secure->setInsecure(); // skip cert verify — saves RAM on ESP32-C3
    client = secure;
  } else {
    client = new WiFiClient();
    if (!client) return false;
  }

  HTTPClient http;
  http.setTimeout(20000);
  http.setReuse(false);

  bool began = useTls ? http.begin(*secure, url) : http.begin(*client, url);
  if (!began) {
    delete client;
    return false;
  }

  int code = http.GET();
  outStatus = code;
  if (code == HTTP_CODE_OK) {
    outBody = http.getString();
  }
  http.end();
  delete client;

  return code == HTTP_CODE_OK && outBody.length() > 0;
}
// AI: end

#else

bool onlineLookupHttpsGet(const char* url, String& outBody, int& outStatus) {
  (void)url;
  outBody = "";
  outStatus = 0;
  return false;
}

#endif
