#pragma once

#include "wled.h"
#include <Arduino.h>
#include "font4x5.h"

#ifdef ARDUINO_ARCH_ESP32
#include <WiFi.h>
#include <time.h>
#include <string.h>
#else
#include <ESP8266WiFi.h>
#include <ESP8266HTTPClient.h>
#include <WiFiClient.h>
#endif

// Default: Launch Library 2, next KSC launch (location id 12), compact list payload (~1–2 KB).
static const char ONLINE_LOOKUP_DEFAULT_API_URL[] PROGMEM =
  "https://ll.thespacedevs.com/2.3.0/launches/upcoming/?limit=1&location__ids=12&mode=list";

class OnlineLookupUsermod : public Usermod {
  private:
    bool initDone = false;
    unsigned long lastUpdate = 0;
    bool updateInProgress = false;
    bool lastFetchFailed = false;
    int lastHttpCode = 0;

    // User configuration
    bool enabled = true;
    int updateInterval = 15; // minutes
    int pageIntervalSeconds = 5;
    bool matrixSerpentine = true;
    bool matrixStartBottom = false;
    bool autoBrightness = true;
    String apiUrl = FPSTR(ONLINE_LOOKUP_DEFAULT_API_URL);

    static const char _name[];
    static const char _enabled[];
    static const char _apiUrl[];

    // Parsed Launch Data
    String launchName = "Loading...";
    String launchDate = "";
    String launchTime = "";
    String launchVehicle = "";
    int launchStatusId = 2; // TBD default
    long launchUnixTime = 0;

    // Display state
    int currentPage = 0;
    unsigned long lastPageSwitch = 0;

  #ifdef ARDUINO_ARCH_ESP32
  TaskHandle_t updateTaskHandle = nullptr;

  // AI: below section was generated by an AI
  // Convert UTC ISO-8601 (...Z) to unix seconds without depending on setenv/TZ.
  long parseISO8601(const char* time_str) {
    struct tm tm;
    memset(&tm, 0, sizeof(tm));
    if (strptime(time_str, "%Y-%m-%dT%H:%M:%SZ", &tm) != NULL) {
        int year = tm.tm_year + 1900;
        int month = tm.tm_mon + 1;
        int day = tm.tm_mday;

        int a = (14 - month) / 12;
        int y = year + 4800 - a;
        int m = month + 12 * a - 3;

        int Jd = day + (153 * m + 2) / 5 + 365 * y + y / 4 - y / 100 + y / 400 - 32045;
        long unixTime = (Jd - 2440588) * 86400L;

        unixTime += tm.tm_hour * 3600L;
        unixTime += tm.tm_min * 60L;
        unixTime += tm.tm_sec;

        return unixTime;
    }
    return 0;
  }

  static void updateTask(void * pvParameters) {
    OnlineLookupUsermod *usermod = (OnlineLookupUsermod *)pvParameters;
    usermod->performUpdate();
    usermod->updateTaskHandle = nullptr;
    vTaskDelete(NULL);
  }

  // Apply Launch Library 2 "results[0]" fields into display state.
  // Supports mode=list (no rocket object): vehicle falls back to text before '|'.
  bool applyLaunchLibraryResult(JsonObject result) {
    String fullName = result["name"] | "Unknown";
    int pipeIdx = fullName.indexOf('|');
    if (pipeIdx > 0 && pipeIdx + 2 < fullName.length()) {
      launchName = fullName.substring(pipeIdx + 2);
      launchName.trim();
    } else {
      launchName = fullName;
    }

    String provider = result["launch_service_provider"]["name"] | "";
    if (provider.length() == 0) provider = result["lsp"]["name"] | "Unknown";
    String rocket = result["rocket"]["configuration"]["name"] | "";

    if (rocket.length() == 0 && pipeIdx > 0) {
      rocket = fullName.substring(0, pipeIdx);
      rocket.trim();
    }

    if (provider == "SpaceX" && rocket.indexOf("Falcon 9") >= 0) launchVehicle = "SpaceX Falcon 9";
    else if (provider == "SpaceX" && rocket.indexOf("Falcon Heavy") >= 0) launchVehicle = "SpX Falcon Heavy";
    else if (provider == "United Launch Alliance") launchVehicle = "ULA " + rocket;
    else if (provider == "Rocket Lab") launchVehicle = "RL " + rocket;
    else if (rocket.length() > 0 && provider != "Unknown") launchVehicle = provider + " " + rocket;
    else if (rocket.length() > 0) launchVehicle = rocket;
    else launchVehicle = provider;

    if (launchVehicle.length() > 16) launchVehicle = launchVehicle.substring(0, 16);

    launchStatusId = result["status"]["id"] | 2;

    const char* net_str = result["net"] | "";
    launchUnixTime = parseISO8601(net_str);

    if (launchUnixTime > 0) {
      time_t localLaunchTime = launchUnixTime + utcOffsetSecs;
      struct tm tm_local;
      gmtime_r(&localLaunchTime, &tm_local);

      char dateBuf[16];
      strftime(dateBuf, sizeof(dateBuf), "%b %d", &tm_local);
      launchDate = String(dateBuf);

      char timeBuf[16];
      strftime(timeBuf, sizeof(timeBuf), "%H:%M", &tm_local);
      launchTime = String(timeBuf);
    }
    return launchName.length() > 0;
  }
  // AI: end
  #endif

  // Implemented in online_lookup.cpp to avoid HTTP_* enum clashes with ESPAsyncWebServer.
  void performUpdate();


  // Set pixel natively handling 2D segments in WLED
  void setPixelXY(int16_t x, int16_t y, uint32_t color) {
    if (x < 0 || x >= 64 || y < 0 || y >= 8) return;
    Segment& seg = strip.getMainSegment();
    if (seg.is2D()) {
      seg.setPixelColorXY(x, y, color);
    } else {
      // Fallback 1D mapping for 8x64 if not configured as 2D
      int local_x = x < 32 ? x : x - 32;
      int base_idx = x < 32 ? 0 : 256;
      bool goingUp = matrixStartBottom;
      if (matrixSerpentine && (local_x % 2 == 1)) goingUp = !goingUp;
      int local_y = goingUp ? (7 - y) : y;
      int index = base_idx + (local_x * 8) + local_y;
      if (index < strip.getLengthTotal()) strip.setPixelColor(index, color);
    }
  }

  void drawChar4x5(int16_t x, int16_t y, char c, uint32_t color) {
    uint32_t bitmap = font4x5[(uint8_t)c];
    for (int col = 0; col < 4; col++) {
      for (int row = 0; row < 5; row++) {
        if (bitmap & (1 << (19 - (row * 4 + col)))) {
          setPixelXY(x + col, y + row, color);
        }
      }
    }
  }


  void drawString4x5(int16_t x, int16_t y, const String& text, uint32_t color) {
    for (unsigned int i = 0; i < text.length(); i++) {
      drawChar4x5(x + (i * 5), y, text[i], color); // 4px char + 1px spacing
    }
  }

  void drawScrollingString4x5(const String& text, uint32_t color, int yOffset = 1) {
    int textWidth = text.length() * 5 - 1;
    int scrollX = 0;

    if (textWidth > 64) {
      int maxScroll = textWidth - 64;
      long cycle = (millis() / 50) % (maxScroll + 40); // 50ms per pixel, 40 ticks padding
      if (cycle < 20) scrollX = 0;
      else if (cycle < 20 + maxScroll) scrollX = cycle - 20;
      else scrollX = maxScroll;
    } else {
      scrollX = -(64 - textWidth) / 2;
    }

    for (unsigned int i = 0; i < text.length(); i++) {
      int charX = (i * 5) - scrollX;
      if (charX > -5 && charX < 64) {
        drawChar4x5(charX, yOffset, text[i], color);
      }
    }
  }

public:
  void setup() override {
    initDone = true;
    lastUpdate = millis() - (updateInterval * 60000UL) + 10000UL;
  }

  void loop() override {
    if (!enabled) return;

    // Page flips must run even while the strip is refreshing; otherwise the
    // display can stick on one page when isUpdating() is true most of the time.
    if (millis() - lastPageSwitch > (pageIntervalSeconds * 1000UL)) {
      lastPageSwitch = millis();
      currentPage = (currentPage + 1) % 4;
    }

    if (strip.isUpdating()) return;

    // Dynamic brightness — stay dim until T-2h (no bump at the 24h window).
    if (autoBrightness) {
      if (launchUnixTime != 0 && toki.second() != 0) {
        long currentUnixTime = toki.second();
        long diff = launchUnixTime - currentUnixTime;

        uint8_t targetBri = 13; // baseline ~5%
        if (diff >= -3600 && diff <= 3600) {
          // T-1h through T+1h
          targetBri = 255;
        } else if (diff > 3600 && diff <= 7200) {
          // T-2h through T-1h
          targetBri = 50;
        }
        // Beyond T-2h (including the 24h window): keep baseline

        if (bri != targetBri) {
          bri = targetBri;
          colorUpdated(CALL_MODE_DIRECT_CHANGE);
        }
      } else {
        if (bri != 13) {
          bri = 13;
          colorUpdated(CALL_MODE_DIRECT_CHANGE);
        }
      }
    }

    // Retry failed fetches after 60s instead of waiting the full update interval.
    unsigned long intervalMs = (unsigned long)((updateInterval <= 0) ? 0 : updateInterval) * 60000UL;
    if (lastFetchFailed && intervalMs > 60000UL) intervalMs = 60000UL;

    if (!updateInProgress && (millis() - lastUpdate > intervalMs)) {
      if (!WLED_CONNECTED) return;

      lastUpdate = millis();
      updateInProgress = true;

      #ifdef ARDUINO_ARCH_ESP32
      if (updateTaskHandle == nullptr) {
        // TLS + JSON needs a larger stack than a plain HTTP GET.
        xTaskCreateUniversal(
          updateTask,
          "OnlineLookup",
          24576,
          this,
          1,
          &updateTaskHandle,
          CONFIG_ARDUINO_RUNNING_CORE
        );
      }
      #else
      performUpdate();
      #endif
    }
  }

  void handleOverlayDraw() override {
    if (!enabled) return;

    for (int i = 0; i < strip.getLengthTotal(); i++) strip.setPixelColor(i, 0);

    long currentUnixTime = toki.second();
    long diffToLaunch = 0;
    bool withinDay = false;
    bool withinTwoHours = false;
    if (launchUnixTime != 0 && currentUnixTime != 0) {
      diffToLaunch = launchUnixTime - currentUnixTime;
      withinDay = (diffToLaunch >= -86400 && diffToLaunch <= 86400);
      withinTwoHours = (diffToLaunch >= -7200 && diffToLaunch <= 7200);
    }

    // Bottom bar uses status color for the whole 24h window. Text stays muted
    // grey until T±2h so the display does not get vivid until then.
    uint32_t barColor = RGBW32(170, 170, 170, 0);
    if (withinDay) {
      if (launchStatusId == 1 || launchStatusId == 3) barColor = RGBW32(0, 255, 0, 0); // Green
      else if (launchStatusId == 4) barColor = RGBW32(255, 0, 0, 0);  // Red
      else if (launchStatusId == 5) barColor = RGBW32(255, 255, 0, 0); // Yellow
    }

    uint32_t textColor = RGBW32(170, 170, 170, 0);
    if (withinTwoHours) textColor = barColor;

    uint32_t greyColor = RGBW32(170, 170, 170, 0);
    if (withinTwoHours && launchStatusId == 3 && diffToLaunch < 0 && diffToLaunch >= -3600) {
      greyColor = RGBW32(0, 255, 0, 0);
    }

    int yOffset = 1; // Center vertically on 8px height (8 - 5 = 3; 3/2 = 1)

    if (currentPage == 0) {
      String dt = launchDate + " " + launchTime;
      dt.replace(" UTC", ""); // Too long for one line
      dt.replace(" EDT", "");
      int textWidth = dt.length() * 5 - 1;
      int startX = (64 - textWidth) / 2;
      if (startX < 0) startX = 0;
      drawString4x5(startX, yOffset, dt, textColor);
    } else if (currentPage == 1) {
      drawScrollingString4x5(launchName, greyColor, yOffset);
    } else if (currentPage == 2) {
      drawScrollingString4x5(launchVehicle, greyColor, yOffset);
    } else {
      if (launchUnixTime == 0 || currentUnixTime == 0) {
        String tStr = "T- TBD";
        int textWidth = tStr.length() * 5 - 1;
        drawString4x5((64 - textWidth) / 2, yOffset, tStr, textColor);
      } else {
        long diff = launchUnixTime - currentUnixTime;
        bool isPast = (diff <= 0);
        if (isPast) diff = -diff;

        long days = diff / 86400;
        long hours = (diff % 86400) / 3600;
        long minutes = (diff % 3600) / 60;
        long seconds = diff % 60;

        String tStr = isPast ? "T+ " : "T- ";

        if (days > 0) {
          tStr += String(days) + "d " + String(hours) + "h";
        } else if (hours > 0) {
          tStr += String(hours) + "h " + String(minutes) + "m";
        } else {
          char buf[12];
          sprintf(buf, "%02ld:%02ld:%02ld", hours, minutes, seconds);
          tStr += String(buf);
        }

        int textWidth = tStr.length() * 5 - 1;
        int startX = (64 - textWidth) / 2;
        if (startX < 0) startX = 0;
        drawString4x5(startX, yOffset, tStr, textColor);
      }
    }

    // Status bar on every page once inside the T±24h window.
    if (withinDay) {
      for (int i = 0; i < 64; i++) {
        setPixelXY(i, 7, barColor);
      }
    }
  }

  void addToJsonInfo(JsonObject& root) override {
    JsonObject user = root["u"];
    if (user.isNull()) user = root.createNestedObject("u");

    JsonArray nameArr = user.createNestedArray(F("Launch"));
    nameArr.add(launchName);

    JsonArray vehArr = user.createNestedArray(F("Vehicle"));
    vehArr.add(launchVehicle);

    JsonArray netArr = user.createNestedArray(F("NET"));
    netArr.add(launchDate + " " + launchTime);

    JsonArray httpArr = user.createNestedArray(F("Fetch"));
    httpArr.add(lastHttpCode);
    httpArr.add(lastFetchFailed ? F("fail") : F("ok"));

    JsonArray pageArr = user.createNestedArray(F("Page"));
    pageArr.add(currentPage);
  }

  void addToConfig(JsonObject& root) override {
    JsonObject top = root.createNestedObject(FPSTR(_name));
    top[FPSTR(_enabled)] = enabled;
    top[FPSTR(_apiUrl)] = apiUrl;
    top["updateInterval_m"] = updateInterval;
    top["pageIntervalSeconds"] = pageIntervalSeconds;
    top["matrixSerpentine"] = matrixSerpentine;
    top["matrixStartBottom"] = matrixStartBottom;
    top["autoBrightness"] = autoBrightness;
  }

  bool readFromConfig(JsonObject& root) override {
    JsonObject top = root[FPSTR(_name)];
    bool configComplete = !top.isNull();

    configComplete &= getJsonValue(top[FPSTR(_enabled)], enabled);
    configComplete &= getJsonValue(top[FPSTR(_apiUrl)], apiUrl);
    configComplete &= getJsonValue(top["updateInterval_m"], updateInterval);
    configComplete &= getJsonValue(top["pageIntervalSeconds"], pageIntervalSeconds);
    configComplete &= getJsonValue(top["matrixSerpentine"], matrixSerpentine);
    configComplete &= getJsonValue(top["matrixStartBottom"], matrixStartBottom);
    configComplete &= getJsonValue(top["autoBrightness"], autoBrightness);

    // Migrate old Mac-proxy URLs to the self-contained Launch Library HTTPS endpoint.
    if (apiUrl.indexOf(F("192.168.")) >= 0 || apiUrl.indexOf(F(":8080")) >= 0 ||
        apiUrl.startsWith(F("http://")) || apiUrl.length() < 8) {
      apiUrl = FPSTR(ONLINE_LOOKUP_DEFAULT_API_URL);
    }

    return configComplete;
  }

  void appendConfigData() override {
    oappend(F("addInfo('")); oappend(String(FPSTR(_name)).c_str()); oappend(F(":apiUrl")); oappend(F("',1,'<i> (HTTPS Launch Library URL)</i>');"));
    oappend(F("addInfo('")); oappend(String(FPSTR(_name)).c_str()); oappend(F(":updateInterval_m")); oappend(F("',1,'<i> (minutes)</i>');"));
    oappend(F("addInfo('")); oappend(String(FPSTR(_name)).c_str()); oappend(F(":pageIntervalSeconds")); oappend(F("',1,'<i> (seconds)</i>');"));
    oappend(F("addInfo('")); oappend(String(FPSTR(_name)).c_str()); oappend(F(":matrixSerpentine")); oappend(F("',1,'<i> (check if matrix snakes up and down)</i>');"));
    oappend(F("addInfo('")); oappend(String(FPSTR(_name)).c_str()); oappend(F(":matrixStartBottom")); oappend(F("',1,'<i> (check if first LED is at bottom)</i>');"));
    oappend(F("addInfo('")); oappend(String(FPSTR(_name)).c_str()); oappend(F(":autoBrightness")); oappend(F("',1,'<i> (auto adjust brightness based on launch proximity)</i>');"));
  }

  uint16_t getId() override {
    return USERMOD_ID_UNSPECIFIED;
  }
};
