#pragma once
#include <Arduino.h>

// Shared clock for scene drawing and element animations.
struct SceneTime {
  unsigned long now = 0;            // millis()
  unsigned long sceneStart = 0;     // millis() when the scene became active
  unsigned long sceneDuration = 0;  // ms; 0 = infinite / unknown
};

// AI: below section was generated by an AI
// Progress of an animation parameterized by start offset and duration,
// both relative to the scene start. Returns 0 before start, 1 after end.
// If durationMs is 0 and the scene has a finite duration, the animation
// spans from (sceneStart + startOffsetMs) to the end of the scene.
inline float animationProgress(const SceneTime& t, unsigned long startOffsetMs, unsigned long durationMs) {
  unsigned long animStart = t.sceneStart + startOffsetMs;
  if (t.now < animStart) return 0.0f;

  unsigned long animDuration = durationMs;
  if (animDuration == 0) {
    if (t.sceneDuration == 0 || t.sceneDuration <= startOffsetMs) return 0.0f;
    animDuration = t.sceneDuration - startOffsetMs;
  }

  unsigned long elapsed = t.now - animStart;
  if (elapsed >= animDuration) return 1.0f;
  return (float)elapsed / (float)animDuration;
}
// AI: end
