#pragma once
#include <Arduino.h>
#include "FontTypes.h"
#include "font_tiny5.h"
#include "font_micro5.h"
#include "font_bytesized.h"
#include "font_jersey10.h"
#include "font_jersey15.h"
#include "font_jersey25.h"
#include "font_pixelify10.h"
#include "font_pixelify11.h"
#include "font_pixelify12.h"
#include "font_silkscreen.h"
#include "font_pixeloid.h"
#include "font_pressstart2p.h"

// AI: below section was generated by an AI
// Case-insensitive, whitespace-tolerant font name lookup.
inline String normalizeFontName(const String& name) {
  String out;
  out.reserve(name.length());
  for (unsigned i = 0; i < name.length(); i++) {
    char c = name.charAt(i);
    if (c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '-' || c == '_') continue;
    if (c >= 'A' && c <= 'Z') c = c - 'A' + 'a';
    out += c;
  }
  return out;
}

inline const BitmapFont* findFontByName(const String& name) {
  String key = normalizeFontName(name);
  if (key.length() == 0) return &font_tiny5;

  if (key == "tiny5") return &font_tiny5;
  if (key == "micro5") return &font_micro5;
  if (key == "bytesized") return &font_bytesized;
  if (key == "jersey10") return &font_jersey10;
  if (key == "jersey15") return &font_jersey15;
  if (key == "jersey25") return &font_jersey25;
  if (key == "pixelify11" || key == "pixelify" || key == "pixelifysans") return &font_pixelify11;
  if (key == "pixelify10") return &font_pixelify10;
  if (key == "pixelify12") return &font_pixelify12;
  if (key == "silkscreen") return &font_silkscreen;
  if (key == "pixeloid" || key == "pixeloidsans") return &font_pixeloid;
  if (key == "pressstart2p" || key == "pressstart" || key == "pressstart2") return &font_pressstart2p;

  Serial.printf("UsermodMatrixDisplay: Unknown font '%s' (normalized '%s'), using tiny5.\n",
                name.c_str(), key.c_str());
  return &font_tiny5;
}
// AI: end
