#pragma once
#include <Arduino.h>
#include "FX.h"
#include "FontTypes.h"
#include "FontRegistry.h"

enum TextAlignment {
    ALIGN_LEFT,
    ALIGN_CENTER,
    ALIGN_RIGHT
};

class Typography {
private:
    static uint8_t glyphWidth(const BitmapFont* font, char c) {
        if (!font || c < 32 || c > 126) return 0;
        return pgm_read_byte(&font->widths[c - 32]);
    }

    // AI: below section was generated by an AI
    // Draw one glyph. scale>=2 expands each font pixel into a scale×scale block.
    static int drawChar(WS2812FX& strip, const BitmapFont* font, int x, int y, char c, uint32_t color, uint8_t scale) {
        if (!font || c < 32 || c > 126) return 0;
        if (scale < 1) scale = 1;

        uint8_t width = glyphWidth(font, c);
        const uint8_t* glyphBase = font->bitmaps + (unsigned)(c - 32) * font->maxWidth * font->bytesPerColumn;

        for (uint8_t col = 0; col < width; col++) {
            for (uint8_t b = 0; b < font->bytesPerColumn; b++) {
                uint8_t bits = pgm_read_byte(&glyphBase[col * font->bytesPerColumn + b]);
                for (uint8_t bit = 0; bit < 8; bit++) {
                    int srcY = (int)b * 8 + bit;
                    if (srcY >= font->height || !(bits & (1 << bit))) continue;

                    for (uint8_t sy = 0; sy < scale; sy++) {
                        for (uint8_t sx = 0; sx < scale; sx++) {
                            int px = x + (int)col * scale + sx;
                            int py = y + srcY * scale + sy;
                            if (px >= 0 && px < 64 && py >= 0 && py < 64) {
                                strip.setPixelColor((unsigned)(py * 64 + px), color);
                            }
                        }
                    }
                }
            }
        }
        return (int)width * scale;
    }
    // AI: end

public:
    static int measureTextWidth(const BitmapFont* font, const String& text, uint8_t scale = 1) {
        if (!font) font = &font_tiny5;
        if (scale < 1) scale = 1;
        int width = 0;
        for (unsigned i = 0; i < text.length(); i++) {
            width += (int)glyphWidth(font, text.charAt(i)) * scale;
        }
        return width;
    }

    static int measureTextHeight(const BitmapFont* font, const String& text, int maxWidth, int lineHeight, uint8_t scale = 1) {
        if (!font) font = &font_tiny5;
        if (scale < 1) scale = 1;
        String currentLine = "";
        int lines = 1;
        int wordStartIndex = 0;

        for (unsigned i = 0; i <= text.length(); i++) {
            bool isSpace = (i < text.length() && text.charAt(i) == ' ');
            bool isEnd = (i == text.length());

            if (isSpace || isEnd) {
                String word = text.substring(wordStartIndex, i);
                String testLine = currentLine.length() == 0 ? word : currentLine + " " + word;
                int lineWidth = measureTextWidth(font, testLine, scale);

                if (lineWidth > maxWidth && currentLine.length() > 0) {
                    lines++;
                    currentLine = word;
                } else if (lineWidth > maxWidth && currentLine.length() == 0) {
                    lines++;
                    currentLine = "";
                } else {
                    currentLine = testLine;
                }
                wordStartIndex = i + 1;
            }
        }
        return lines * lineHeight;
    }

    static void drawText(WS2812FX& strip, const BitmapFont* font, const String& text,
                         int startX, int startY, int maxWidth, int lineHeight,
                         TextAlignment align, uint32_t color, uint8_t scale = 1) {
        if (!font) font = &font_tiny5;
        if (scale < 1) scale = 1;
        String currentLine = "";
        int currentY = startY;
        int wordStartIndex = 0;

        for (unsigned i = 0; i <= text.length(); i++) {
            bool isSpace = (i < text.length() && text.charAt(i) == ' ');
            bool isEnd = (i == text.length());

            if (isSpace || isEnd) {
                String word = text.substring(wordStartIndex, i);
                String testLine = currentLine.length() == 0 ? word : currentLine + " " + word;
                int lineWidth = measureTextWidth(font, testLine, scale);

                if (lineWidth > maxWidth && currentLine.length() > 0) {
                    commitLine(strip, font, currentLine, startX, currentY, maxWidth, align, color, scale);
                    currentLine = word;
                    currentY += lineHeight;
                } else if (lineWidth > maxWidth && currentLine.length() == 0) {
                    commitLine(strip, font, word, startX, currentY, maxWidth, align, color, scale);
                    currentLine = "";
                    currentY += lineHeight;
                } else {
                    currentLine = testLine;
                }
                wordStartIndex = i + 1;
            }
        }

        if (currentLine.length() > 0) {
            commitLine(strip, font, currentLine, startX, currentY, maxWidth, align, color, scale);
        }
    }

    // Top-most lit row for a single glyph, inclusive, in unscaled font pixels.
    // Returns font->height if the glyph has no ink.
    static int glyphInkTop(const BitmapFont* font, char c) {
        if (!font || c < 32 || c > 126) return font ? font->height : 0;
        uint8_t width = glyphWidth(font, c);
        const uint8_t* glyphBase = font->bitmaps + (unsigned)(c - 32) * font->maxWidth * font->bytesPerColumn;
        int top = font->height;
        for (uint8_t col = 0; col < width; col++) {
            for (uint8_t b = 0; b < font->bytesPerColumn; b++) {
                uint8_t bits = pgm_read_byte(&glyphBase[col * font->bytesPerColumn + b]);
                for (uint8_t bit = 0; bit < 8; bit++) {
                    int srcY = (int)b * 8 + bit;
                    if (srcY >= font->height || !(bits & (1 << bit))) continue;
                    if (srcY < top) top = srcY;
                }
            }
        }
        return top;
    }

    // Bottom-most lit row for a single glyph, exclusive, in unscaled font pixels.
    // Returns 0 if the glyph has no ink.
    static int glyphInkBottom(const BitmapFont* font, char c) {
        if (!font || c < 32 || c > 126) return 0;
        uint8_t width = glyphWidth(font, c);
        const uint8_t* glyphBase = font->bitmaps + (unsigned)(c - 32) * font->maxWidth * font->bytesPerColumn;
        int bottom = 0;
        for (uint8_t col = 0; col < width; col++) {
            for (uint8_t b = 0; b < font->bytesPerColumn; b++) {
                uint8_t bits = pgm_read_byte(&glyphBase[col * font->bytesPerColumn + b]);
                for (uint8_t bit = 0; bit < 8; bit++) {
                    int srcY = (int)b * 8 + bit;
                    if (srcY >= font->height || !(bits & (1 << bit))) continue;
                    int exclusive = srcY + 1;
                    if (exclusive > bottom) bottom = exclusive;
                }
            }
        }
        return bottom;
    }

    // Inclusive top of ink for a string on one line (no wrapping), scaled.
    static int measureInkTop(const BitmapFont* font, const String& text, uint8_t scale = 1) {
        if (!font) font = &font_tiny5;
        if (scale < 1) scale = 1;
        int top = font->height;
        for (unsigned i = 0; i < text.length(); i++) {
            int t = glyphInkTop(font, text.charAt(i));
            if (t < top) top = t;
        }
        if (top >= font->height) return 0;
        return top * scale;
    }

    // Exclusive bottom of ink for a string on one line (no wrapping), scaled.
    static int measureInkHeight(const BitmapFont* font, const String& text, uint8_t scale = 1) {
        if (!font) font = &font_tiny5;
        if (scale < 1) scale = 1;
        int bottom = 0;
        for (unsigned i = 0; i < text.length(); i++) {
            int b = glyphInkBottom(font, text.charAt(i));
            if (b > bottom) bottom = b;
        }
        return bottom * scale;
    }

    // Vertical span of wrapped text using ink height on the last line.
    static int measureBlockInkHeight(const BitmapFont* font, const String& text, int maxWidth, int lineHeight, uint8_t scale = 1) {
        if (!font) font = &font_tiny5;
        if (scale < 1) scale = 1;
        String currentLine = "";
        int linesBeforeLast = 0;
        int wordStartIndex = 0;

        for (unsigned i = 0; i <= text.length(); i++) {
            bool isSpace = (i < text.length() && text.charAt(i) == ' ');
            bool isEnd = (i == text.length());
            if (!isSpace && !isEnd) continue;

            String word = text.substring(wordStartIndex, i);
            String testLine = currentLine.length() == 0 ? word : currentLine + " " + word;
            int lineWidth = measureTextWidth(font, testLine, scale);

            if (lineWidth > maxWidth && currentLine.length() > 0) {
                linesBeforeLast++;
                currentLine = word;
            } else if (lineWidth > maxWidth && currentLine.length() == 0) {
                linesBeforeLast++;
                currentLine = "";
            } else {
                currentLine = testLine;
            }
            wordStartIndex = i + 1;
        }

        int lastInk = measureInkHeight(font, currentLine, scale);
        if (lastInk <= 0) lastInk = scaledLineHeight(font, scale);
        return linesBeforeLast * lineHeight + lastInk;
    }

    // Suggested line height for a font at a given pixel scale.
    static int scaledLineHeight(const BitmapFont* font, uint8_t scale) {
        if (!font) font = &font_tiny5;
        if (scale < 1) scale = 1;
        return (int)font->defaultLineHeight * scale;
    }

private:
    static void commitLine(WS2812FX& strip, const BitmapFont* font, const String& line,
                           int startX, int y, int maxWidth, TextAlignment align, uint32_t color, uint8_t scale) {
        int lineWidth = measureTextWidth(font, line, scale);
        int x = startX;

        if (align == ALIGN_CENTER) {
            x = startX + (maxWidth - lineWidth) / 2;
        } else if (align == ALIGN_RIGHT) {
            x = startX + (maxWidth - lineWidth);
        }

        for (unsigned i = 0; i < line.length(); i++) {
            x += drawChar(strip, font, x, y, line.charAt(i), color, scale);
        }
    }
};
