#pragma once
#include "wled.h"
#include <PubSubClient.h>
#include <WiFiClientSecure.h>
#include "Scene.h"
#include "NotificationScene.h"
#include "WarningScene.h"
#include "DefaultScene.h"

#if __has_include("secrets/mqtt_iot_secrets.h")
#include "secrets/mqtt_iot_secrets.h"
#endif

#ifndef MATRIX_IOT_SECRETS_PRESENT
#define MATRIX_IOT_SECRETS_PRESENT 0
#endif

// AI: below section was generated by an AI
// Completes the unfinished PubSubClient path so MQTT on mqttTopic can drive
// notification scenes. Core WLED MQTT remains disabled on this IDF V5 build.
// Always keeps a DefaultScene (black) active when no notification is showing.
// Supports a queued sequence via {"scenes":[...]} in one MQTT/HTTP payload.
// AWS IoT Core (TLS 8883) when secrets/mqtt_iot_secrets.h is present; plain
// MQTT on 1883 remains available via runtime mqttServer/mqttPort retarget.
class UsermodMatrixDisplay : public Usermod {
  private:
    bool enabled = true;
#if MATRIX_IOT_SECRETS_PRESENT
    String mqttServer = MQTT_IOT_ENDPOINT;
    int mqttPort = MQTT_IOT_PORT;
    String mqttTopic = MQTT_IOT_TOPIC;
    String mqttClientId = MQTT_IOT_CLIENT_ID;
#else
    String mqttServer = "192.168.1.93";
    int mqttPort = 1883;
    String mqttTopic = "wled/matrix/scene";
    String mqttClientId = "";
#endif

    DefaultScene defaultScene;
    Scene* activeScene = nullptr;
    unsigned long sceneStartTime = 0;
    unsigned long sceneDuration = 0; // 0 = infinite
    bool hasDrawn = false;

    // Pending scenes from a multi-scene payload (JSON objects, serialized).
    static constexpr size_t SCENE_QUEUE_MAX = 8;
    static constexpr size_t SCENE_JSON_MAX = 768;
    String sceneQueue[SCENE_QUEUE_MAX];
    size_t sceneQueueHead = 0;
    size_t sceneQueueLen = 0;

    WiFiClient wifiClient;
    WiFiClientSecure wifiClientSecure;
    PubSubClient mqttClient;
    unsigned long lastMqttReconnectAttempt = 0;
    static constexpr unsigned long MQTT_RECONNECT_INTERVAL = 5000;
    static constexpr size_t MQTT_PAYLOAD_MAX = 2048;
    static UsermodMatrixDisplay* instance;

    bool useTls() const {
#if MATRIX_IOT_SECRETS_PRESENT
      return mqttPort == 8883;
#else
      return false;
#endif
    }

    void configureMqttTransport() {
#if MATRIX_IOT_SECRETS_PRESENT
      if (useTls()) {
        // DER credentials — Tasmota mbedtls is built without PEM_PARSE_C.
        wifiClientSecure.setCACertDer(MQTT_IOT_ROOT_CA_DER, MQTT_IOT_ROOT_CA_DER_LEN);
        wifiClientSecure.setCertificateDer(MQTT_IOT_DEVICE_CERT_DER, MQTT_IOT_DEVICE_CERT_DER_LEN);
        wifiClientSecure.setPrivateKeyDer(MQTT_IOT_PRIVATE_KEY_DER, MQTT_IOT_PRIVATE_KEY_DER_LEN);
        mqttClient.setClient(wifiClientSecure);
        return;
      }
#endif
      mqttClient.setClient(wifiClient);
    }

    void clearSceneQueue() {
      sceneQueueHead = 0;
      sceneQueueLen = 0;
      for (size_t i = 0; i < SCENE_QUEUE_MAX; i++) sceneQueue[i] = String();
    }

    bool enqueueScene(JsonObject sceneObj) {
      if (sceneObj.isNull() || sceneQueueLen >= SCENE_QUEUE_MAX) return false;
      String json;
      serializeJson(sceneObj, json);
      if (json.length() == 0 || json.length() >= SCENE_JSON_MAX) return false;
      size_t idx = (sceneQueueHead + sceneQueueLen) % SCENE_QUEUE_MAX;
      sceneQueue[idx] = json;
      sceneQueueLen++;
      return true;
    }

    void showDefaultScene() {
      if (activeScene != nullptr && activeScene != &defaultScene) {
        delete activeScene;
      }
      activeScene = &defaultScene;
      sceneDuration = 0;
      hasDrawn = false;
      Serial.println("UsermodMatrixDisplay: Showing default scene.");
    }

    // Start one scene now (does not touch the queue).
    void startScene(JsonObject matrixParams) {
      String type = matrixParams["type"] | "notification";
      Serial.printf("UsermodMatrixDisplay: Scene type = %s\n", type.c_str());

      if (type == "notification" || type == "warning") {
        if (activeScene != nullptr && activeScene != &defaultScene) {
          delete activeScene;
        }
        activeScene = (type == "warning")
          ? static_cast<Scene*>(new WarningScene())
          : static_cast<Scene*>(new NotificationScene());
        hasDrawn = false;
        activeScene->updateParams(matrixParams);

        sceneStartTime = millis();
        if (matrixParams.containsKey("duration")) {
          sceneDuration = matrixParams["duration"].as<unsigned long>();
          Serial.printf("UsermodMatrixDisplay: Created %s with duration %lu ms.\n",
                        type.c_str(), sceneDuration);
        } else {
          sceneDuration = 0;
          Serial.printf("UsermodMatrixDisplay: Created %s with infinite duration.\n", type.c_str());
        }
      } else if (type == "clear") {
        Serial.println("UsermodMatrixDisplay: Clearing scene.");
        showDefaultScene();
      } else if (type == "config") {
        // config-only; nothing to display
      }
    }

    // Advance to next queued scene, or default if queue empty.
    void advanceSceneQueue() {
      if (sceneQueueLen == 0) {
        showDefaultScene();
        return;
      }

      String json = sceneQueue[sceneQueueHead];
      sceneQueue[sceneQueueHead] = String();
      sceneQueueHead = (sceneQueueHead + 1) % SCENE_QUEUE_MAX;
      sceneQueueLen--;

      StaticJsonDocument<SCENE_JSON_MAX> doc;
      DeserializationError err = deserializeJson(doc, json);
      if (err) {
        Serial.printf("UsermodMatrixDisplay: Queued scene JSON error: %s\n", err.c_str());
        advanceSceneQueue();
        return;
      }
      Serial.printf("UsermodMatrixDisplay: Advancing queue (%u remaining).\n",
                    (unsigned)sceneQueueLen);
      startScene(doc.as<JsonObject>());
    }

    // Runtime MQTT broker retarget (serial / HTTP state / MQTT payload).
    void applyMqttConfig(JsonObject matrixParams) {
      bool changed = false;
      if (matrixParams.containsKey("mqttServer")) {
        mqttServer = matrixParams["mqttServer"].as<String>();
        changed = true;
      }
      if (matrixParams.containsKey("mqttPort")) {
        mqttPort = matrixParams["mqttPort"].as<int>();
        changed = true;
      }
      if (matrixParams.containsKey("mqttTopic")) {
        mqttTopic = matrixParams["mqttTopic"].as<String>();
        changed = true;
      }
      if (matrixParams.containsKey("mqttClientId")) {
        mqttClientId = matrixParams["mqttClientId"].as<String>();
        changed = true;
      }
      if (!changed) return;

      if (mqttClient.connected()) mqttClient.disconnect();
      configureMqttTransport();
      mqttClient.setServer(mqttServer.c_str(), mqttPort);
      lastMqttReconnectAttempt = 0;
      configNeedsWrite = true;  // persist broker settings across reboot
      Serial.printf("UsermodMatrixDisplay: MQTT config -> %s:%d topic %s tls=%d\n",
                    mqttServer.c_str(), mqttPort, mqttTopic.c_str(), useTls() ? 1 : 0);
    }

    // Switch STA network via serial/HTTP (password is never logged).
    void applyWifiConfig(JsonObject matrixParams) {
      if (!matrixParams.containsKey("wifiSSID")) return;

      const char* ssid = matrixParams["wifiSSID"];
      const char* pass = matrixParams.containsKey("wifiPass")
                       ? matrixParams["wifiPass"].as<const char*>()
                       : "";
      if (!ssid || !ssid[0]) return;
      if (multiWiFi.empty()) multiWiFi.resize(1);

      strlcpy(multiWiFi[0].clientSSID, ssid, 33);
      strlcpy(multiWiFi[0].clientPass, pass ? pass : "", 65);
      selectedWiFi = 0;
      forceReconnect = true;
      configNeedsWrite = true;
      Serial.printf("UsermodMatrixDisplay: WiFi -> SSID '%s' (reconnect + save)\n", ssid);
    }

    // Shared by JSON API and MQTT: create/update/clear the active scene,
    // or replace the queue with a multi-scene sequence.
    void applyMatrixParams(JsonObject matrixParams) {
      if (matrixParams.isNull()) return;

      applyMqttConfig(matrixParams);
      applyWifiConfig(matrixParams);

      JsonArray scenes = matrixParams["scenes"].as<JsonArray>();
      if (!scenes.isNull() && scenes.size() > 0) {
        clearSceneQueue();
        bool started = false;
        for (JsonVariant v : scenes) {
          JsonObject s = v.as<JsonObject>();
          if (s.isNull()) continue;
          if (!started) {
            startScene(s);
            started = true;
          } else if (!enqueueScene(s)) {
            Serial.println("UsermodMatrixDisplay: Scene queue full; dropping scene.");
          }
        }
        if (!started) {
          Serial.println("UsermodMatrixDisplay: scenes[] had no valid objects.");
        } else {
          Serial.printf("UsermodMatrixDisplay: Sequence started (%u queued after current).\n",
                        (unsigned)sceneQueueLen);
        }
        return;
      }

      const bool hasScene = matrixParams.containsKey("type")
                         || matrixParams.containsKey("title")
                         || matrixParams.containsKey("message");
      if (!hasScene) return;

      String type = matrixParams["type"] | "notification";
      // A new single scene or clear replaces any pending sequence.
      clearSceneQueue();
      if (type == "clear") {
        showDefaultScene();
        return;
      }
      startScene(matrixParams);
    }

    // Parse MQTT payload (wrapped MatrixDisplay object or bare scene params).
    void handleMqttMessage(char* topic, byte* payload, unsigned int length) {
      if (!enabled) return;
      if (mqttTopic.length() && strcmp(topic, mqttTopic.c_str()) != 0) return;

      if (length >= MQTT_PAYLOAD_MAX) {
        Serial.println("UsermodMatrixDisplay: MQTT payload too large.");
        return;
      }

      char buf[MQTT_PAYLOAD_MAX];
      memcpy(buf, payload, length);
      buf[length] = '\0';

      StaticJsonDocument<MQTT_PAYLOAD_MAX> doc;
      DeserializationError err = deserializeJson(doc, buf);
      if (err) {
        Serial.printf("UsermodMatrixDisplay: MQTT JSON parse error: %s\n", err.c_str());
        return;
      }

      JsonObject matrixParams = doc["MatrixDisplay"].as<JsonObject>();
      if (matrixParams.isNull()) {
        matrixParams = doc.as<JsonObject>();
      }
      if (matrixParams.isNull()) {
        Serial.println("UsermodMatrixDisplay: MQTT payload missing scene params.");
        return;
      }

      Serial.println("UsermodMatrixDisplay: MQTT message received.");
      applyMatrixParams(matrixParams);
    }

    static void mqttCallback(char* topic, byte* payload, unsigned int length) {
      if (instance) instance->handleMqttMessage(topic, payload, length);
    }

    String resolveClientId() {
      if (mqttClientId.length()) return mqttClientId;
      String id = F("wled-matrix-");
      id += String((uint32_t)ESP.getEfuseMac(), HEX);
      return id;
    }

    // Non-blocking reconnect with subscribe; caller enforces backoff.
    bool reconnectMqtt() {
      // AWS IoT TLS rejects handshakes when the RTC is still at epoch (NTP off/unsynced).
      if (useTls()) {
        time_t now = time(nullptr);
        if (now < 1700000000) { // ~2023-11-14
          Serial.printf("UsermodMatrixDisplay: waiting for NTP before TLS MQTT (time=%ld)\n",
                        (long)now);
          return false;
        }
        wifiClientSecure.setHandshakeTimeout(45);
        wifiClientSecure.setTimeout(45);
      }

      configureMqttTransport();
      mqttClient.setServer(mqttServer.c_str(), mqttPort);
      String clientId = resolveClientId();
      Serial.printf("UsermodMatrixDisplay: Connecting to MQTT %s:%d (tls=%d id=%s)...\n",
                    mqttServer.c_str(), mqttPort, useTls() ? 1 : 0, clientId.c_str());

      if (mqttClient.connect(clientId.c_str())) {
        Serial.printf("UsermodMatrixDisplay: MQTT connected, subscribing to %s\n", mqttTopic.c_str());
        mqttClient.subscribe(mqttTopic.c_str());
        return true;
      }

      Serial.printf("UsermodMatrixDisplay: MQTT connect failed (state=%d).\n", mqttClient.state());
#if MATRIX_IOT_SECRETS_PRESENT
      if (useTls()) {
        char errBuf[128];
        int err = wifiClientSecure.lastError(errBuf, sizeof(errBuf));
        Serial.printf("UsermodMatrixDisplay: TLS lastError=%d %s\n", err, errBuf);
      }
#endif
      return false;
    }
    // AI: end

  public:
    UsermodMatrixDisplay() : mqttClient(wifiClient) {}

    void setup() {
      instance = this;
      showDefaultScene();
      configureMqttTransport();
      mqttClient.setCallback(mqttCallback);
      mqttClient.setBufferSize(MQTT_PAYLOAD_MAX);
#if MATRIX_IOT_SECRETS_PRESENT
      // Ensure SNTP runs even if /cfg.json left ntp.en=false (common on fresh boards).
      ntpEnabled = true;
      configTime(0, 0, "pool.ntp.org", "time.nist.gov");
      Serial.printf("UsermodMatrixDisplay: Instasign IoT MQTT defaults -> %s:%d\n",
                    mqttServer.c_str(), mqttPort);
#endif
    }

    void loop() {
      if (activeScene != nullptr && activeScene != &defaultScene && sceneDuration > 0) {
        if (millis() - sceneStartTime > sceneDuration) {
          Serial.println("UsermodMatrixDisplay: Scene duration expired.");
          advanceSceneQueue();
        }
      }

      // AI: below section was generated by an AI
      if (!enabled || !WLED_CONNECTED) return;

      if (!mqttClient.connected()) {
        unsigned long now = millis();
        if (now - lastMqttReconnectAttempt >= MQTT_RECONNECT_INTERVAL) {
          lastMqttReconnectAttempt = now;
          reconnectMqtt();
        }
      } else {
        mqttClient.loop();
      }
      // AI: end
    }

    void handleOverlayDraw() override {
      if (enabled && activeScene != nullptr) {
        if (!hasDrawn) {
          Serial.println("UsermodMatrixDisplay: handleOverlayDraw executing for the first time on new scene!");
          hasDrawn = true;
        }
        SceneTime time;
        time.now = millis();
        time.sceneStart = sceneStartTime;
        time.sceneDuration = sceneDuration;
        // Overlay our scene over whatever WLED is currently rendering
        activeScene->draw(strip, time);
      }
    }

    void readFromJsonState(JsonObject& root) override {
      JsonObject matrixParams = root["MatrixDisplay"];
      if (!matrixParams.isNull()) {
        Serial.println("UsermodMatrixDisplay: Found MatrixDisplay in JSON payload.");
        applyMatrixParams(matrixParams);
      }
    }

    void addToConfig(JsonObject& root) override {
      JsonObject top = root.createNestedObject("MatrixDisplay");
      top["enabled"] = enabled;
      top["mqttServer"] = mqttServer;
      top["mqttPort"] = mqttPort;
      top["mqttTopic"] = mqttTopic;
      top["mqttClientId"] = mqttClientId;
    }

    bool readFromConfig(JsonObject& root) override {
      JsonObject top = root["MatrixDisplay"];
      bool configComplete = !top.isNull();
      configComplete &= getJsonValue(top["enabled"], enabled);
      configComplete &= getJsonValue(top["mqttServer"], mqttServer);
      configComplete &= getJsonValue(top["mqttPort"], mqttPort);
      configComplete &= getJsonValue(top["mqttTopic"], mqttTopic);
      getJsonValue(top["mqttClientId"], mqttClientId); // optional for older configs
#if MATRIX_IOT_SECRETS_PRESENT
      // Old cfg.json may still point at a LAN broker (1883). Prefer Instasign IoT
      // when secrets are compiled in; runtime JSON can still retarget to 1883.
      if (mqttPort != MQTT_IOT_PORT) {
        mqttServer = MQTT_IOT_ENDPOINT;
        mqttPort = MQTT_IOT_PORT;
        mqttTopic = MQTT_IOT_TOPIC;
        mqttClientId = MQTT_IOT_CLIENT_ID;
        Serial.println("UsermodMatrixDisplay: migrated cfg to Instasign IoT MQTT.");
      }
#endif
      // Apply broker settings so Usermod Settings changes take effect on next reconnect.
      if (!top.isNull()) {
        if (mqttClient.connected()) mqttClient.disconnect();
        configureMqttTransport();
        mqttClient.setServer(mqttServer.c_str(), mqttPort);
      }
      return configComplete;
    }
};

UsermodMatrixDisplay* UsermodMatrixDisplay::instance = nullptr;
